### ISSUE TITLE
Example for ModelSelect2MultipleWidget dependent_fields

### ISSUE THREAD

**Issue by siavashdarkvision** [codingjoe/django-select2#10]
**Goal**
Given multiple countries selected in a parent _ModelSelect2MultipleWidget_, display all cities within the aforementioned countries in a child _ModelSelect2MultipleWidget_.

**Problem**
I am not sure how to do this given the examples. Does the package support this feature? If not, can you point out the major steps that I would need to do in order to implement this functionality?

**Code Snippet**

**models.py**
```
class Country(models.Model):
    name = models.CharField(max_length=255)

class City(models.Model):
    name = models.CharField(max_length=255)
    country = models.ForeignKey('Country', related_name="cities")
```

**forms.py**
```
class InterestingCities(forms.Form):
    countries = forms.ModelChoiceField(
        label = "Countries",
        widget = ModelSelect2MultipleWidget(
            model = Country,
            search_fields = ['name__icontains'],
        ),
        queryset = Country.objects.all(),
    )
    
    cities = forms.ModelChoiceField(
        label = "Cities",
        widget = ModelSelect2MultipleWidget(
            model = City,
            search_fields = ['name__icontains'],
            dependent_fields = {'country': 'country'}, # What should this line be? Is this the only thing that needs to change?
            max_results = 500,
        ),
        queryset = City.objects.all(),
    )
```

**Comment by cvipul** [comment]
@siavashdarkvision - https://github.com/applegrew/django-select2/issues/403
Discussion on the older home of this repo.

**Comment by siavashdarkvision** [comment]
I ended up writing my own custom form from scratch. Would have been nice if it was implemented given that there is nothing else out there.

**Comment by Dakdeniz** [comment]
I found a solution to multiplechoicefield dependency by inserting two lines of code into js file like below.
It seems a little dirty but works in my case, with django-filters.

```
$.each(dependentFields, function (i, dependentField) {
    result[dependentField] = $("[name=" + dependentField + "]",$element.closest("form")).val();

    if (Array.isArray(result[dependentField])) {
        result[dependentField] = result[dependentField].toString();   
    }
});
```

**Comment by codingjoe** [comment]
Hi there, the feature should work now since v7.7.0 Best, Joe
