### ISSUE TITLE
Many2Many Placeholder

### ISSUE THREAD

**Issue by nikolas-dev** [codingjoe/django-select2#105]
`$('.django-select2').djangoSelect2({placeholder: 'Select an option'});`

Generate placeholder for foreignkey field. But not generated in many2many

**Comment by codingjoe** [comment]
Hi @nikolas-dev,

Thank you for reaching out. I am having a bit of trouble to follow you. Would you be so kind as to providing additional information about what's not working? Maybe even including an example?

Best Joe

**Comment by nikolas-dev** [comment]
widgets:
```
class SampleDocumentSelect2Widget(ModelSelect2MultipleWidget):
    model = SampleDocument
    search_fields = ['name__icontains', ]
```

models:
```
class SampleDocument(TimeStamp):
    name = models.CharField(max_length=100)

class SampleSubmission(TimeStamp):
    documents = models.ManyToManyField(SampleDocument, blank=True, verbose_name='Reference Documents')
```

output
![image](https://user-images.githubusercontent.com/15107827/141490293-bc4ab2cc-9e88-4fb7-b290-7b7e38df8b12.png)

see output without placeholder. though I used `$('.django-select2').djangoSelect2({placeholder: 'Select an option'});`

**Comment by codingjoe** [comment]
Using the JS code worked, or it didn't?
> `$('.django-select2').djangoSelect2({placeholder: 'Select an option'});`

**Comment by nikolas-dev** [comment]
did not work
