### ISSUE TITLE
What is the effect of not using a proper cache setup?

### ISSUE THREAD

**Issue by abeforgit** [codingjoe/django-select2#11]
I'm using the default Django cache setup (that is to say, no cache config at all).

Is it just a performance hit? Or are there circumstances in which the select would not work?

**Comment by jpm92** [comment]
I'm also interested on this. Last time I used django-select2 I never set up any cache config nor saw it in the docs as a requirement.
Is this new or I just missed something the first time? It worked perfectly anyway.

**Comment by abeforgit** [comment]
It's only anecdotal evidence, but so far it has worked perfectly without any cache setup in my current project

**Comment by quinceleaf** [comment]
Anecdotal from me: I developed an internal business app 2(?) years ago that made heavy use of django-select2. I hadn't bothered to set up any cache.

In development (local machine) and then initially deployed on a server rack within our facility, no issues. But when several months later we deployed to external server, the latency on the ajax response was noticable (2-3s roundtrip) and management was very unhappy. 

Then read the cache portion of the documentation, set up a redis cache for django-select2, and latency for the UI dropped to 2-3ms. Have always used the cache option on every project using it since

**Comment by abeforgit** [comment]
That's good enough for me, thanks for your insights. My usecase is absolutely tiny so I won't bother with a cache until it starts biting. Made a pr to clarify this in the docs #16

**Comment by jpm92** [comment]
> Anecdotal from me: I developed an internal business app 2(?) years ago that made heavy use of django-select2. I hadn't bothered to set up any cache.
> 
> In development (local machine) and then initially deployed on a server rack within our facility, no issues. But when several months later we deployed to external server, the latency on the ajax response on the autocomplete was noticable (2-3s roundtrip) and management was very unhappy.
> 
> Then read the cache portion of the documentation, set up a redis cache on external server for django-select2, and latency for the autocomplete dropped to 2-3ms. Have always used the cache option on every project using it since, never had any latency problems again

Thanks for your input, I'm not gonna have a heavy use of it, so I guess I can live without proper cache.

**Comment by rez0n** [comment]
I have a database table with 10K entries to use in the select2 field, on the local environment it works correctly and fast, after the deployment to the server select2 lost 1/3 of all entries on search, it just does not appear on typing.
Redis cache fixed this.

**Comment by codingjoe** [comment]
Hey there, sorry I somehow missed the questions. There isn't a performance difference (at least not a reasonable one). The main difference is only relevant for systems that use multiple application servers. In that case, you will need a cache that is consistent across all those servers. That being said, if you have a setup that large, you probably already have a dedicated Redis or memcached server.

In terms of performance, I personally used this package on tables with millions of records. As long as your database can handle your search query, there is no limit.
