### ISSUE TITLE
Support for to_field_name

### ISSUE THREAD

**Issue by eriktelepovsky** [codingjoe/django-select2#111]
Hello,

**Describe the bug**
ModelSelect2Widget is not compatible with/does not fully respect ``to_field_name`` attribute of ModelChoiceField.

**Code Snippet**
```
locality = django_filters.ModelChoiceFilter(
        label=_('Locality'),
        queryset=Locality.objects.all(),
        to_field_name='slug',
        widget=ModelSelect2Widget(
            model=Locality,
            queryset=Locality.objects.all(),
            search_fields=['title__icontains'],
            attrs={'data-minimum-input-length': 0}
        )
    )
```

**To Reproduce**
1. I actually use django-filter to create form but the you can see the point
2. use form field
3. the autocomplete search works correctly, you can see fetched options in the select
4. submit form
5. the submitted value is not valid in the form, you can see the error message under the select "Select a valid choice. That choice is not one of the available choices."

It is because it expects "slug" from the "to_field_name" but get always "id" from AutoResponseView instead.

**Expected behavior**
to_field_name (slug in my case) should be sent as value and valid choice in the select is expected.

**Screenshots**
Current error state:
![image](https://user-images.githubusercontent.com/2685808/147647056-f9053638-c1ae-410f-beb0-8ebe68c91653.png)

Expected:
![image](https://user-images.githubusercontent.com/2685808/147647132-e7b19567-e9f6-4610-9446-9bb8e3c1be32.png)

**Current fix:**
My current workaround works with custom ``data_view`` which returns obj.slug instead of obj.pk:

```
class AutoSlugResponseView(AutoResponseView):
    def get(self, request, *args, **kwargs):
        """
        Return a :class:`.django.http.JsonResponse`.

        Example::

            {
                'results': [
                    {
                        'text': "foo",
                        'id': "bar"
                    }
                ],
                'more': true
            }

        """
        self.widget = self.get_widget_or_404()
        self.term = kwargs.get("term", request.GET.get("term", ""))
        self.object_list = self.get_queryset()
        context = self.get_context_data()
        return JsonResponse(
            {
                "results": [
                    {"text": self.widget.label_from_instance(obj), "id": obj.slug}
                    for obj in context["object_list"]
                ],
                "more": context["page_obj"].has_next(),
            }
        )
``` 

but I expect it to be automatic.

Thank you.

**Comment by codingjoe** [comment]
Hi @eriktelepovsky,

Thank you for reaching out. I believe this is a duplicate to #100, right?

Best Joe

**Comment by codingjoe** [comment]
I fixed it recently in Django itself, I haven't got the time to port this here. Honestly, if you have time and want to contribute, I'd really welcome a helping hand.
