### ISSUE TITLE
Select2Heavy queries wrong url

### ISSUE THREAD

**Issue by manuelkappler** [codingjoe/django-select2#122]
**Describe the bug**
When using ModelSelect2, the GET-Request gets routed to `current/url?field_id=correct_field_id` instead of `/select2/fields/auto.json?field_id=correct_field_id`

I'm somewhat flustered by it, since I can't find a similar issue being described anywhere, but it completely wrecks the functionality of select2-widgets on my site. With the quick fix below, it can be salvaged, however it needs to be reapplied on every update.

**Environment**
Problem already existed on Python 3.6, Django 3.xy and django_select2 4.xy. Today I updated to Python 3.8, Django 4.0, django_select2 7.10.0, but the problem persists.

**Expected behavior**
Request sent to `/select2/fields/auto.json`

**Fix**
By adding the line

`url: $element.data('ajax-Url'),`

inside `initHeavy` in `django_select2/static/django_select2.js`

```var initHeavy = function ($element, options) {
    var settings = $.extend({
      ajax: {
        url: $element.data('ajax-Url'),
        data: function (params) {
          var result = {
            term: params.term,
            page: params.page,
            field_id: $element.data('field_id')
          }
```

the request gets routed properly.

**Comment by codingjoe** [comment]
Hi @manuelkappler,

Thanks for reaching out. I am not 100% sure I understood the problem, but the `Select2Heavy` does not define AJAX URL. You will always have to provide one, via `widget.data_url` or by overwriting `widget.get_url`. If you are looking for a widget that is pointing towards the built-in views (`/select2/fields/auto.json`), you will need to use the `Model`-widgets.

I hope my answer helps. If you have any further questions, feel free to reach out.

Best
Joe

**Comment by manuelkappler** [comment]
Hey Joe, thanks for the quick response. Sorry for the confusion, I am actually using ModelSelect2Widgets in my forms, however the URL isn't passed down to the widget properly.

Can you maybe explain how the widget is supposed to end up getting the ajax-Url without the line I added above?

**Comment by codingjoe** [comment]
Sure, select2 is almost entirely configurable via data attributes. For nested sub-keys, you'll need to add double dashes. It's all documented over here: https://select2.org/configuration/data-attributes#nested-subkey-options
