### ISSUE TITLE
'djangoSelect2 is not a function' error, although fields already initialized with it successfully

### ISSUE THREAD

**Issue by quinceleaf** [codingjoe/django-select2#15]
**Goal**
Using formsets that include field widgets using django 3.1.2 and django-select2 7.4.2. Trying to implement an "Add Another" functionality. **Inquiring if I am missing some understanding of manual initialization of django-select2.**

**Problem**
Cloning the form rows is done. Have not been successful **manually** initializing django-select2 for new rows. Attempting to use django-select2 via the jquery plugin
```
$('.django-select2').djangoSelect2();
```
method as specified in the documentation triggers the error `djangoSelect2 is not a function`, even though:

- there are on same page fields already rendered and successfully working that have been instantiated at page load using djangoSelect2
- both `jquery-3.5.1.min.js` and `django-select2.js` appear in ChromeDevTools sources tab
- `{{form.media.js}}` and `{{formset.media.js}}` are included on template
- no other errors are reported in the console

My understanding is that the reported error should only occur if jquery or django-select2 were not installed. What would you suggest I look into to resolve?

**Code Snippets**

```
  $("#add-row").click(function (e) {
    e.preventDefault();
    let prefix = "lines"
    let totalForms = `#id_${prefix}-TOTAL_FORMS`
    let formIndex  = parseInt($(totalForms).val());
    var newRow = $("#form-template").clone()
    newRow.removeAttr("id")
    reindexForm(newRow, formIndex);
    $(totalForms).val(formIndex + 1)
    newRow.appendTo('#target').removeClass("d-none")
    $('.django-select2').djangoSelect2()
  });
```

**Comment by codingjoe** [comment]
Hi @quinceleaf,

Sorry for responding so late. I somehow didn't get notified.

Your problem is strange. I agree your example snippet should work. Would you mind sending me your full HTML code, so I could further debug the problem?

Best,
Joe
