### ISSUE TITLE
CSS issue on widget

### ISSUE THREAD

**Issue by SylvainMartel** [codingjoe/django-select2#157]
**Describe the bug**
Hi, I updated my Django app to Django 3.2 and updated django-select to the latest 7.10.1 too.  Since then, I have a small display glitch with select2 widgets where the field is truncated and we cannot see the items text in it.  If I remove "display: inline-block" as a css attribute, it display correctly.

forms.py
```python
merchandise_cat = forms.ModelChoiceField(label='Merchandise Category', queryset=merchandise_category.objects.all().order_by('cat_name'),
                                             widget=ModelSelect2Widget(
        model=merchandise_category,
        search_fields=['cat_name__icontains'],
        attrs={'data-minimum-input-length': 0},
    ),
        required=False)
    merchandise = forms.ModelChoiceField(label='Merchandise', queryset=Merchandise.objects.all().order_by('item_name'),
                                         widget=ModelSelect2Widget(
        model=Merchandise,
        search_fields=['item_name__icontains'],
        dependent_fields={'merchandise_cat': 'item_category'},
        attrs={'data-minimum-input-length': 0},
        max_results=500,
    ),
        required=False)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/9009158/194936100-d0e3467b-f0a4-4095-bc00-ca25e96ac3ee.png)
![image](https://user-images.githubusercontent.com/9009158/194936195-e854c56b-8cb8-4820-83a1-9f3a928f84e6.png)

![image](https://user-images.githubusercontent.com/9009158/194936171-4460945a-2241-434b-b739-d43fdf0328a3.png)
![image](https://user-images.githubusercontent.com/9009158/194936236-457de985-e8da-4ede-9101-7e1af0d3b638.png)

**Comment by henryleonard** [comment]
I have the same issue with a Select2 multiple. Forcing the select2-container to display inline (rather than inline-block) fixes the input, but the drop down list still has width: 17px. Alternatively, I found that removing any divs or spans which are enclosing the Select2 input makes it usable again (but the Select2 input now has 100% width).

**Comment by SylvainMartel** [comment]
I found the problem, and it wasn't Select2.  I updated crispy-forms too but forgot to update the bootstrap css file for the theme to 5.  After I did that, the widget display fine once more
