### ISSUE TITLE
Duplicated select2 input when rendering

### ISSUE THREAD

**Issue by jpm92** [codingjoe/django-select2#17]
Looking at so many uncommented issues makes me not very hoping of fixing it anytime soon, but I'm facing a problem that I can't seem to figure out. The select2 input is rendered twice, I get two search fields, specifically 
two of these:

`<span class="select2 select2-container select2-container--default" dir="ltr" data-select2-id="1" style="width: 100%;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="-1" aria-disabled="false" aria-labelledby="select2-id_form-0-producto-container"><span class="select2-selection__rendered" id="select2-id_form-0-producto-container" role="textbox" aria-readonly="true"><span class="select2-selection__placeholder">Busque productos</span></span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>`

![Captura de pantalla de 2020-10-30 11-14-35](https://user-images.githubusercontent.com/55791361/97693663-c9a4a700-1aa1-11eb-8c08-dffdec2acae4.png)

This is my django code:

```
models.py
class Producto(models.Model):

    nombre_amistoso = models.CharField(
        max_length=40,
        help_text=_('Nombre amigable del producto.')
    )
    nombre_fabricante = models.CharField(
        max_length=60,
        help_text=_(
            'Nombre real del producto, tal como lo conoce el fabricante.'
        )
    )
    fabricante = models.ForeignKey(
        'Fabricante',
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    referencia = models.CharField(
        max_length=25,
        help_text=_('Referencia del fabricante.')
    )

forms.py
class ProductoWidget(s2forms.ModelSelect2Widget):
    """ Widget especial creado con libreria django-select2.
    Busca según los campos especificados en serach_fields. """

    search_fields = [
        "nombre_amistoso__icontains",
        "nombre_fabricante__icontains",
        "referencia__icontains",
    ]


class ArticuloForm(forms.ModelForm):
    """ Este formulario se utiliza para agregar articulos a la pizarra. """

    class Meta:
        model = Articulo
        fields = ['producto', 'unidades']
        widgets = {
            "producto": ProductoWidget(
                {'data-language': 'es',
                 'data-placeholder': 'Busque productos',
                 'data-width': '100%',
                 }
            ),
        }

views.py

def NuevaNota(request):
    ArticuloFormset = formset_factory(ArticuloForm)
    if request.method == "POST":
    # bunch of code

    else:
        articulos = ArticuloFormset()
        nota = NotaForm()
        context = {
            'articulos': articulos,
            'nota': nota
        }
        return render(request, "gestion/anotar.html", context)
```

The inputs work perfectly, they search in the fields they have to. Only they render in duplicate.
Also, the **data-language** attribute seems to not be taking any effect (still in english).

I hope @codingjoe can take a look at the open issues anytime soon.
Thanks a lot for taking over, let me know If I can be helpful in any manner, I'd love to.
J.

**update:** I add also the html template.
```
base_generic.html

  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon -->
    <link rel="icon" href="{% static '/img/favicon.ico' %}">
    <!-- CSS links -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Iconos FontAwesome -->
    <link rel="stylesheet" type="text/css" href="{% static 'gestion/css/styles.css' %}">
    {% block extracss %}{% endblock %}
    <script src="https://kit.fontawesome.com/434ec950ab.js" crossorigin="anonymous"></script>
    <!-- - -->
    <title>{% block titulo %}Gestión de pedidos TERSTEM{% endblock %}</title>
  </head>
  <body>
    ...
    <!-- JS Scripts -->
    {% block jquery %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock %}
    <!-- - -->
  </body>

anotar.html

{% extends "base_generic.html" %}
{% block extracss %}
  {{ articulos.media.css}}
{% endblock %}
{% block titulo %}Nueva nota | PEDIDOS TERSTEM{% endblock %}

{% block contenido %}
<form>
  {% csrf_token %}
    {{ articulos.management_form }}
  <div class="form-group">
    {% for articulo in articulos %}
        {{ articulo.as_p }}
    {% endfor %}
  </div>
  <div class="form-group">
    {{ nota.entrega }}
  </div>
</form>
{% block jquery %}
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
{% endblock %}
{% block extrajs %}
  {{ articulos.media.js }}
{% endblock %}
{% endblock %}
```

**Comment by CleitonDeLima** [comment]
Hi @jpm92 , 
If you can show your html it may be easier to see what is going on.
I already had this problem because of css. If you already have a standard select2 css, try calling {{form.media.css}} later.

**Comment by jpm92** [comment]
Hi, @CleitonDeLima, I've updated the issue with the template. I've tried moving around the css with no success.

Thanks for your help!

**Comment by CleitonDeLima** [comment]
As it is a formset, how is your `empty_form` in the template? I say this because select2 may be initializing 2x, once for `empty_form` and once when adding the new form, check this out for me.

**Comment by jpm92** [comment]
This is what gets rendered:
```
<form>
  <input type="hidden" name="csrfmiddlewaretoken" value="xcRWQC6UvL5M2U6SJjfEHiXw6sOsUpczA2Z9oj2q1jS3x6Xm8nzjBrTw2N5GuXZx">
  <input type="hidden" name="form-TOTAL_FORMS" value="1" id="id_form-TOTAL_FORMS">
  <input type="hidden" name="form-INITIAL_FORMS" value="0" id="id_form-INITIAL_FORMS">
  <input type="hidden" name="form-MIN_NUM_FORMS" value="0" id="id_form-MIN_NUM_FORMS">
  <input type="hidden" name="form-MAX_NUM_FORMS" value="1000" id="id_form-MAX_NUM_FORMS">
  <div class="form-group">
    <p>
      <label for="id_form-0-producto">Producto:</label>
      <select name="form-0-producto" data-minimum-input-length="2" data-allow-clear="false" data-ajax--url="/select2/fields/auto.json" data-ajax--cache="true" data-ajax--type="GET" data-language="es" data-placeholder="Busque productos" data-width="100%" id="id_form-0-producto" class="django-select2 django-select2-heavy select2-hidden-accessible" data-field_id="IjY0NmFmMzhmLWY2OGItNGUzNi1iNmQwLWFiOGMzYTZlZmJkMiI:1kYX5S:MYWzN7H2e9UoBJbhLpidcal6tD6T9gzcLY5Zfi24gXQ" data-select2-id="id_form-0-producto" tabindex="-1" aria-hidden="true">
      </select>
      <span class="select2 select2-container select2-container--default" dir="ltr" data-select2-id="1" style="width: 100%;">
        <span class="selection">
          <span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="-1" aria-disabled="false" aria-labelledby="select2-id_form-0-producto-container">
            <span class="select2-selection__rendered" id="select2-id_form-0-producto-container" role="textbox" aria-readonly="true">
              <span class="select2-selection__placeholder">Busque productos</span></span><span class="select2-selection__arrow" role="presentation">
                <b role="presentation"></b>
              </span>
            </span>
          </span>
          <span class="dropdown-wrapper" aria-hidden="true"></span>
        </span>
        <span class="select2 select2-container select2-container--default" dir="ltr" data-select2-id="1" style="width: 100%;">
          <span class="selection">
            <span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-disabled="false" aria-labelledby="select2-id_form-0-producto-container">
              <span class="select2-selection__rendered" id="select2-id_form-0-producto-container" role="textbox" aria-readonly="true">
                <span class="select2-selection__placeholder">Busque productos</span>
              </span>
              <span class="select2-selection__arrow" role="presentation">
                <b role="presentation"></b>
              </span>
            </span>
          </span>
          <span class="dropdown-wrapper" aria-hidden="true">
          </span>
        </span>
      </p>
      <p>
        <label for="id_form-0-unidades">Unidades:</label>
        <input type="number" name="form-0-unidades" value="1" id="id_form-0-unidades">
      </p>
    </div>
    <!-- Other irrelevant (I think) stuff -->
  </form>
```

**Comment by jpm92** [comment]
I've tried the following with no success:
  - Use a regular form instead of a formset.
  - Use a pure base ModelSelect2  widget.
  - Use a Select2 widget.

They all render a duplicated fully functional element, with the exception of Select2 widget which renders two select2 fields, but they fail to search (there is no options inside).

Funny enough, If I use it with another Model it works perfectly (for example, NotaForm, which is also in the code snippet).

It's really driving me nuts.

Thanks for any help,
JP.

**Comment by jpm92** [comment]
Hello, @CleitonDeLima and @codingjoe , I'm sorry to be a bummer, but without Select2 it doesn't make sense to go on with this project, I hope you can someday check it out, I would be inmensely thankful (specially since most probably it will be a stupid mistake on my part).

Meanwhile I'll try to implement my own version of a select2 plugin with a custom view to handle ajax, but I don't have much expectations...

Cheers and thanks for all the contributions!

**Comment by CleitonDeLima** [comment]
@jpm92 How is your code to add forms to the formset?

**Comment by jpm92** [comment]
Thanks for your response @CleitonDeLima , if you mean dynamically adding forms, I'm not doing it at all (yet). 
Anyway, it looks like it has nothing to do with formsets. I've tried switching to a regular form and it still renders twice :/

**Comment by CleitonDeLima** [comment]
I already had this problem, that time I realized that the fields with selec2 were being initialized in javascript 2 times (`$('.django-select2').djangoSelect2()`). Without seeing the code in detail I don't know where the problem is.

**Comment by jpm92** [comment]
Sorry, @CleitonDeLima what code exactly would you need to check? Should I paste you the whole <script> part? 

Thanks again!

**Comment by CleitonDeLima** [comment]
@jpm92 is the code on github?

**Comment by jpm92** [comment]
Yes it is, I'll make you a collaborator, thanks 👍

**Comment by jpm92** [comment]
In case this helps someone:
obviously it was my fault. I opened a block before closing the previous one in the django template. I basically nested by mistake one block inside another (which is not how django works). Big thanks to @CleitonDeLima who reviewed my code and pointed it out 🎉

**Comment by codingjoe** [comment]
Wow, cool, thanks @CleitonDeLima for sorting this out. I love it when problems solve themselves, still I am sorry took me so long to answer. I kind of got married this weekend, and therefore was preoccupied.

**Comment by jpm92** [comment]
Wow, big congrats then! 🎉  And thanks a lot for taking time to review the issues even without all the hassle 😄
