### ISSUE TITLE
Bug in documentation for ModelSelect2TagWidget

### ISSUE THREAD

**Issue by pawnhearts** [codingjoe/django-select2#170]
There is a bug in documentation for ModelSelect2TagWidget. It should be     cleaned_values = list(pks) instead of      cleaned_values = list(values)

**Comment by codingjoe** [comment]
Hi @pawnhearts,

Thank you for reaching out. Excellent documentation is key for an open-source project. I sincerely appreciate your contribution here. That being said, I am not 100% sure I know where that line is? I'd welcome you to open a PR that changes the lines in question. I will make sure to review it quickly and deploy a new documentation.

Thanks!
Joe

**Comment by pawnhearts** [comment]
For some reason I can't find that part of documentation in sources. Here is the link https://django-select2.readthedocs.io/en/latest/django_select2.html#django_select2.forms.ModelSelect2TagWidget 4th line from bottom in the example. It should be cleaned_values = list(pks). Otherwise it creates 2 duplicate tags and then fails on optgroups functions.

I was very confused until realized logic in that example is wrong.

**Comment by codingjoe** [comment]
Hi @pawnhearts, the documentation is built form Python doc-strings: https://github.com/codingjoe/django-select2/blob/4770f069e5dd6137f725f4e16095cfd4cf9d78b6/django_select2/forms.py#L583-L608

**Comment by codingjoe** [comment]
Resolved in #177 

Thanks, @pawnhearts, I really appreciate the help!
