### ISSUE TITLE
data_view and data_url do not work as class attrs

### ISSUE THREAD

**Issue by CleitonDeLima** [codingjoe/django-select2#171]
**Is your feature request related to a problem? Please describe.**
Following this [docstring](https://github.com/CleitonDeLima/django-select2/blob/master/django_select2/forms.py#L315-L320), `data_view` or `data_url` doesn't work as expected, both are defined at class initialization.

**Describe the solution you'd like**
I couldn't do a test but I believe it's simple defining them in the class with the expected default value passing to init

**Comment by codingjoe** [comment]
I merged your PR, thanks @CleitonDeLima
