### ISSUE TITLE
{{form.media.*}}  return None on Django 3.1.*

### ISSUE THREAD

**Issue by mbambadev** [codingjoe/django-select2#19]
I work with django 3.1.* + python 3.8
I have correctly follow all steps on get started tutorial
but when i try to render form django-select2 not render js and css file
In my template i have try {{form.media.js}} and {{form.media.css}} nothing done !
I have try {{form.media.render_js}} and {{form.media.render_css}} i get empty list

I want to know please what i missing...

**Comment by mbambadev** [comment]
Sorry sorry 
After many search i have forgotten 's' to widget in class Meta parameter.
Nice Day !

**Comment by codingjoe** [comment]
Alrighty, let me know if you have any other questions.
