### ISSUE TITLE
Is Bootstrap5 supported?

### ISSUE THREAD

**Issue by hendrikschneider** [codingjoe/django-select2#193]
**Goal**
Please describe your goal in all detail. What are you trying to do

Use this select2 with bootstrap5.

**Problem**
Please describe your problem in all detail. Where are you struggling?

Is there some documentation on how to use Bootstrap5 with django-select2?

**Code Snippet**
Please provide a code snippet of your problem.

**Comment by CleitonDeLima** [comment]
Hi @hendrikschneider 

https://apalfrey.github.io/select2-bootstrap-5-theme/

https://django-select2.readthedocs.io/en/latest/django_select2.html#django_select2.conf.Select2Conf.THEME

**Comment by hendrikschneider** [comment]
@CleitonDeLima thank you a lot!
