### ISSUE TITLE
tagging in the django-select2

### ISSUE THREAD

**Issue by ovt00** [codingjoe/django-select2#2]
I try to use ModelSelect2TagWidget and I receive value list, where is id for existing items and name for new. How can I undestand in the method value_from_datadict what is what? My name of new item can be "1" for example and 1 is id for current item in the queryset

**Comment by Iran-110** [comment]
Hi, ```value_from_dictdata``` is a method that takes the ```ModelSelect2TagWidget``` data from HTML and return the data in a format that is compatible with ```FormField```. On the other hand, Tag Fields usually implementes with ```ManyToManyField``` in the model which corresponds to ```ModelMultipleChoiceField``` in the form.

So, we have three things: ```widget``` <-> ```form field``` <-> ```model field```.

```value_from_datadict``` is responsible to convert ```widget``` output to ```form field``` input.
But the options which already exists has ```integer``` type as the ```primary key``` value whereas new options has ```string``` type as the ```title```.

So, we must override this method to translate ```widget``` output correctly.


You can use the example of this subsection:

https://django-select2.readthedocs.io/en/latest/django_select2.html#django_select2.forms.ModelSelect2TagWidget

In the line (```cleaned_values.append(self.queryset.create(title=val).pk)```) ```title``` is the name of your model field. you can change it.
