### ISSUE TITLE
Use Dropdown widget in dynamically added/deleted formset factory.

### ISSUE THREAD

**Issue by BenAkko** [codingjoe/django-select2#20]
**Goal**
Use django-select2 dropdown widget in dynamically added/deleted formset factory.

**Problem**
The widget loads for each formset, and works properly for the first form, however future forms do not show the dropdown when clicked on. This is non-Admin view.

https://github.com/applegrew/django-select2/issues/606#issuecomment-633102623

On this linked comment, Joe asks if the form is being added dynamically, which mine is - is this the cause of the issue?

**Code Snippet**
Not sure which part of my code is causing this, and don't want to add everything, so can add this in the future if needed.

**Comment by codingjoe** [comment]
Hi @BenAkko,

Apologies for the delayed response. I somehow didn't get any notifications for a while.

Regarding your questions, you need to initialize the new select fields once the form has been injected into your DOM.

```javascript
// … inject your formser
$('.django-select2').djangoSelect2() // initialize select2 fields
```

This should solve your problem.

Best,
Joe
