### ISSUE TITLE
Focus is not set to child .select2-search__field when selecting parent drop down in Django 4.1

### ISSUE THREAD

**Issue by selected-pixel-jameson** [codingjoe/django-select2#200]
**Describe the bug**
There is a UX issue when I click on the filter the select2 input field doesn't gain focus. I'm unable to tab to put focus down to that field either. I have to use the mouse to manually click on that second input field in the drop down after I just clicked on the input. 

Notice in this screenshot how there is no cursor in the second input? 
![Screenshot 2023-01-12 at 9 50 43 AM](https://user-images.githubusercontent.com/28204537/212115513-173ed0e4-8133-4b9d-810a-0072c098d471.png)

And this is from our current production site. Notice how the cursor is showing in the screenshot?
![Screenshot 2023-01-12 at 9 55 18 AM](https://user-images.githubusercontent.com/28204537/212115617-1b80d651-dcd9-4567-9ead-8425defea5e1.png)

While this seems like a insignificant issue it is actually rather large because end-users of the admin panel are using this filter very often and having to make a secondary click is just going to cause issues.  I would be willing to submit a pull request for this, but I'm not even sure where to start.

**Comment by codingjoe** [comment]
Hi @selected-pixel-jameson,

Thank you for reaching out. I am afraid this particular issue is not related to this Django integration but is based on a buck in Select2 itself. See also: https://github.com/select2/select2/issues/5993

Best Joe
