### ISSUE TITLE
jQuery is not defined in the docs

### ISSUE THREAD

**Issue by amureki** [codingjoe/django-select2#212]
**Describe the bug**
Greetings!
Thanks for the library!
I was looking for something in the docs, but search is loading endlessly for me.
In devtools I noticed the error.

**Exception & Traceback**
```
Uncaught ReferenceError: jQuery is not defined
    at search.html?q=my_search_term:298:7
(
```

**To Reproduce**
https://django-select2.readthedocs.io/en/latest/search.html?q=my_search_term

**Expected behavior**
Search results are appearing on the page

**Comment by codingjoe** [comment]
Hi @amureki,

I am afraid this is a Sphinx error, or rather an error with ReadTheDocs and their theme. We don't customize the theme in any way. Therefore, I am afraid there is nothing I can do from my side.

Cheers!

**Comment by amureki** [comment]
True, dug a bit deeper and it is indeed something with version incompatibility. The issue is filed here, linking it for the reference:

https://github.com/readthedocs/readthedocs.org/issues/10263
