### ISSUE TITLE
Update CONTRIBUTING.rst

### ISSUE THREAD

**Issue by neuged** [codingjoe/django-select2#214]
**Is your feature request related to a problem? Please describe.**

Currently `CONTRIBUTING.rst` instructs me to run `python setup.py` to build and test, but there is no `setup.py`

**Describe the solution you'd like**

I would like command line examples on how to build/test/lint the project and the documentation locally.

**Describe alternatives you've considered**

I have looked at `setup.cfg` and `pyproject.toml`. I see that the build tool is flit. I can make up a venv and run `flit install --deps all`, but then `pytest` still fails with `No module named 'selenium'`. I can sort of get a sphinx build of the documentation running with `sphinx-build -b html docs /tmp/test` but that doesn't pull in the code commentary correctly.

**Comment by codingjoe** [comment]
Thanks for alerting me about this. I rewrote this bit, to reflect the modern packaging setup.
