### ISSUE TITLE
Empty DropBox with ModelSelect2Widget

### ISSUE THREAD

**Issue by MrInker** [codingjoe/django-select2#224]
Hello.
Empty DropBox with ModelSelect2Widget.
I'm using such a variable in my Form:

  ```Python
  project_region = forms.ModelChoiceField(
        queryset=Regions.objects.all().order_by('region_code'),
        widget=ModelSelect2Widget(
            model=Regions,
            search_fields=['region_code__icontains', 'region_name__icontains'],
            attrs={
                'data-width': '100%',
                'data-placeholder': 'Выберите регион',
                'data-format-selection': '{text}',
                'data-minimum-input-length': 0,
            }
        )
    )
```

However, the drop-down menu is empty, but the search  and scroll works, and as far as I can see, there is data but it is not displayed in dropbox.

![django-select](https://github.com/codingjoe/django-select2/assets/59257682/61bf8379-b84c-47d4-a4f6-d43870b6e2eb)

I request your assistance, thank you very much.

**Comment by sorspro** [comment]
Working Example:
```py
class ClassNameWidget(ModelSelect2MultipleWidget):
    search_fields = ["name__icontains", "name__istartswith"]
    queryset = ClassName.objects.all().order_by('name')
    dependent_fields = {'project': 'project'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.attrs = {
            'data-width': '100%',
            'data-placeholder': 'Select at least one ClassName',
            'data-format-selection': '{text}',
            'data-minimum-input-length': 0,
        }
```

**Comment by MrInker** [comment]
Thanks for the answer, but it doesn't work.

That is, if you use ModelSelect2MultipleWidget, the values ​​appear in the drop-down list, but I do not need multiple selection.
When using ModelSelect2Widget, the problem is the same.

And I noticed that when using 'data-minimum-input-length': 3 , a message that you need to enter at least 3 characters appears in a narrow field right next to the expanded drop-down list.

very similar to a problem with styles?

**Comment by MrInker** [comment]
I'm very sorry for the inconvenience)
Found a problem in my css
