### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by re4lfl0w** [codingjoe/django-select2#275]
### Bug Description

If you add data-ajax--delay in Select2MultipleWidget, Select Widget does not work properly.

```
class PartyWithMultipleWidget(s2forms.Select2MultipleWidget):
    search_fields = [
        "name__icontains",
    ]
```

```
widgets = {
  'board_tags': BoardTagsWidget(
    attrs={
        'data-ajax--delay': 500,
    }
  ),
}
```

[06/Apr/2024 06:42:41] "GET /board/free/5/edit?term=%EA%B0%80%EC%9E%90&_type=query&q=%EA%B0%80%EC%9E%90 HTTP/1.1" 200 22679

query success to server but not visible result
if delete 'data-ajax--delay' in form. success. but client get many requests.

### Steps to Reproduce

Bug Description

### Expected Behavior

I want to get result

**Comment by codingjoe** [comment]
Hi @re4lfl0w,

Thank you for reaching out. The issues you are describing appears to be related to `Select2` the JavaScript package we are using. All we are doing, is setting a data attribute, which does work, right? I would encourage you to reach out to their community on GitHub. I am sure they can help you solve this.

Cheers!
Joe
