### ISSUE TITLE
i18n is broken due to missing jQuery import in media 🐛 

### ISSUE THREAD

**Issue by mardukbp** [codingjoe/django-select2#292]
### Bug Description

When using django-select2 in the Django Admin (regardless of the value of settings.LANGUAGE_CODE) the corresponding i18n file (e.g. en.js) throws the following exception in the brower console:

```js
TypeError: Cannot read properties of undefined (reading 'define')
    at en.js:3:106
    at en.js:3:755
```

The problem is that jquery.init.js is loaded before this file. In order to load it afterwards [this line](https://github.com/codingjoe/django-select2/blob/07ea4b8cf996eb587fd3dacf4361bd579d83e8e2/django_select2/forms.py#L158) has to be replaced with:

```python
            js=select2_js + i18n_file + ["admin/js/jquery.init.js"] + ["django_select2/django_select2.js"],
```

### Steps to Reproduce

1. Create the following model:

```python
from django.db import models

class Person(models.Model):
    title = models.CharField(max_length=10, choices=[('Dr.', 'Dr.'), ('Rep.', 'Rep.')])
```

2. Create the following admin for the model:

```python
from django.contrib import admin
from django import forms

from django_select2.forms import Select2Widget

from .models import Person


class PersonForm(forms.ModelForm):
    class Meta:
        widgets = {
            'title': Select2Widget
        }


@admin.register(Person)
class PersonAdmin(admin.ModelAdmin):
    form = PersonForm
```

3. Visit the admin page for the model (admin/app/person/add/)

4. Open the browser console and find the exception thrown in en.js

### Expected Behavior

No exception is thrown and the i18n works as expected

**Comment by codingjoe** [comment]
@mardukbp can you check how Django handles this for the autocomplete field in admin integration? Otherwise, please don't hesitate to provide a patch. Cheers! Joe

**Comment by mardukbp** [comment]
I learned how to fix this in the [source code](https://github.com/django/django/blob/main/django/contrib/admin/widgets.py#L588) of AutocompleteMixin :)  

Patch submitted :)

**Comment by codingjoe** [comment]
🤙 nice 🤙
