### ISSUE TITLE
Installing via pipenv Fails

### ISSUE THREAD

**Issue by allidoisace** [codingjoe/django-select2#31]
**Goal**
Trying to install Django-Select2.

**Problem**
```
pipenv install django-select2
```
```
ERROR: Could not find a version that matches django<2.0.0,==1.11.27,>=1.11,>=1.8,>=1.8.0,>=2.2
```

**Code Snippet**
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
dj-database-url = "==0.5.0"
Django = "==1.11.27"
gunicorn = "==19.9.0"
"psycopg2-binary" = "==2.7.5"
djangorestframework = "==3.8.2"
whitenoise = "==3.3.1"
python-decouple = "==3.1"
django-tenants = "==1.3.4"
brotlipy = "==0.7.0"
django-el-pagination = "==3.2.4"
django-debug-toolbar = "==1.9.1"
"boto3" = "==1.7.66"
django-storages = "==1.6.6"
pillow = "==5.2.0"
redis = "*"
celery = "*"
xlrd = "*"
defusedxml = "*"
django-inlinecss = "*"
django-select2 = "*"

[dev-packages]

[requires]
python_version = "3.6.10"
```

**Comment by codingjoe** [comment]
Hi @allidoisace,

Thanks for reaching out. I am afraid we dropped Django 1.11 support over a year ago, as extended support for Django 1.11 was reached EOL in April 2020. Might I suggest updating Django first, for security reason and afterwards update to a compatible django-select2 version.

Best,
Joe

**Comment by allidoisace** [comment]
Thanks, I went through quite a few releases and didn't see there were major versions being dropped.

**Comment by codingjoe** [comment]
It was dropped in version 7, see https://github.com/applegrew/django-select2/releases/tag/7.0.0
