### ISSUE TITLE
I cannot set a value to django-select2 ModelSelect2Widget using val() function

### ISSUE THREAD

**Issue by eruiz67** [codingjoe/django-select2#72]
In my django app I have a CenterModel and a ProvinceModel, each center has a province_id field. I have define a form for Center using ModelSelect2Widget (django_select2) for province_id. I want to set the selected value to the province_id field in the template using javascript but the following code is not working:

```
$("#id_province_id").val(response.province_id)
$('#id_province_id').trigger('change'); 
```

but these lines are not working, they are NOT setting the value to the province_id field. Instead if the field has some previosly selected value the '.val()' funtion clears that value. I double checked and the response.province_id is storing a valid province id. Why I cannot set a value to the selct field? I am working with django-select2==7.7.1
```

class CenterModel(models.Model):

    name = models.CharField(verbose_name=_("Nombre"), max_length=50, unique=True,blank=False, null=False)

    province_id = models.ForeignKey("ProvinceModel", verbose_name=_("Provincia"),
                                                 blank=True, null=True, on_delete=models.SET_NULL,
                                                 related_name="centers")

    municipality_id = models.ForeignKey("MunicipalityModel", verbose_name=_("Municipio"),
                                                 blank=True, null=True, on_delete=models.SET_NULL,
                                                 related_name="centers")



   
from django_select2.forms import ModelSelect2Widget

class CenterForm(forms.ModelForm):

    class Meta:
        model = CenterModel
        exclude = ("id",)
        widgets = {
            'name':forms.TextInput(attrs={'class': 'form-control'}),
            'province_id' : ModelSelect2Widget(model=ProvinceModel, queryset=ProvinceModel.objects.filter(),
                                            search_fields=['des_prov__icontains'],
                                            attrs={'style': 'width: 100%;'}),
            'municipality_id' : ModelSelect2Widget(model=MunicipalityModel, queryset=MunicipalityModel.objects.filter(),
                                            search_fields=['municipio__icontains'],
                                            dependent_fields={'province_id': 'cod_prov'},
                                            attrs={'style': 'width: 100%;'}),
            }


```

**Comment by codingjoe** [comment]
Hi @eruiz67,

Thank you for reaching out. I am afraid this is not related to this package, but the the JavaScript package Select2. I also recomment you check out their documentation on how to select a value https://select2.org/programmatic-control/add-select-clear-items

Best,
Joe

**Comment by Vinay9838** [comment]
Hi Same issue for me also .  
i tried for multiselect $('#id_employee').select2(['760','26']).trigger('change') but not working  . If i am trying for jquery select2 only then it worked but for django-select2 its not working .

**Comment by Vinay9838** [comment]
> Hi @eruiz67,
> 
> Thank you for reaching out. I am afraid this is not related to this package, but the the JavaScript package Select2. I also recomment you check out their documentation on how to select a value https://select2.org/programmatic-control/add-select-clear-items
> 
> Best,
> Joe

Hi Same issue for me also .
i tried for multiselect $('#id_employee').select2(['760','26']).trigger('change') but not working . If i am trying for jquery select2 only then it worked but for django-select2 its not working .
I think its a bug in package .

**Comment by Vinay9838** [comment]
I got it  why options were not selected through jquery . since this package options are dynamic   means if we search for option only that time option will appear else not . So for this we can create new option in dropdown and set  .

`  if ($('#id_employee').find("option[value='" + 760 + "']").length) {
    $('#id_employee').val(760).trigger('change');
} else {
    // Create a DOM Option and pre-select by default
    var newOption = new Option('Tester',760, true, true);
    // Append it to the select
    $('#id_employee').append(newOption).trigger('change');
}`
