### ISSUE TITLE
Clearing value of dependent fields 

### ISSUE THREAD

**Issue by tyctor** [codingjoe/django-select2#79]
Clearing value of dependent fields not working for multiple dependent fields

for me this selector will not match if there are multiple field names
```
$('[data-select2-dependent-fields=' + name + ']').each(function () {
          $(this).val('').trigger('change')
})
```

what is working for me is to change it like this
```
$("[data-select2-dependent-fields~='" + name + "']").each(function () {
          $(this).val('').trigger('change')
})
```

**Comment by codingjoe** [comment]
Hi @tyctor,
Thank you for reaching out. This could be related to spaces in the data value.
Can you try with quotation marks but without the tilde? Anyhow, if you have a working solution, please don't hesitate to open a pull-request, I would very much welcome the contribution.
Best
Joe

**Comment by quevon24** [comment]
Having same issue, as @tyctor said, with this change now works fine:

```
$('[data-select2-dependent-fields~=' + name + ']').each(function () {
          $(this).val('').trigger('change')
        })
```

**Comment by codingjoe** [comment]
Thanks @quevon24, that's good feedback. Now someone just needs to find time to turn it into a patch. Maybe you'd be intersted?
