### ISSUE TITLE
Switch to tail.select

### ISSUE THREAD

**Issue by codingjoe** [codingjoe/django-select2#83]
little reminder to consider switching to tail.select as a more lightweight alternative to select2.

**Comment by CleitonDeLima** [comment]
https://tom-select.js.org/

**Comment by CleitonDeLima** [comment]
@codingjoe 
do you think about changing the select2 or adapting to accept select2 and others?

**Comment by codingjoe** [comment]
@CleitonDeLima I would love to use a package that doesn't rely on jQuery. jQuery hasn't aged well, since all that was good about it has made its way into ES.

**Comment by frague59** [comment]
Select2 does not need jQuery any more, maybe it's time to move out of using jQuery in the django-select2 ?

**Comment by CleitonDeLima** [comment]
> Select2 does not need jQuery any more, maybe it's time to move out of using jQuery in the django-select2 ?

When did this change happen? for me this is new

**Comment by frague59** [comment]
Sorry, it's a mistake, it still uses jquery...

**Comment by codingjoe** [comment]
Since Select2 is integrated in Django itself, I will stick to the library.
