### ISSUE TITLE
Cache is hit but SQL still executed

### ISSUE THREAD

**Issue by andyp05** [codingjoe/django-select2#9]
Using the ModelSelect2Widget in a form and when I hit the dropdown multiple times, it hits the DB every time.

I am using redis cache and when I inspect it, the key is there. 

In views.py
```
    def get_widget_or_404(self):
        ...
        try:
            key = signing.loads(field_id)
        except BadSignature:
            raise Http404('Invalid "field_id".')
        else:
            cache_key = "%s%s" % (settings.SELECT2_CACHE_PREFIX, key)
            widget_dict = cache.get(cache_key)
            if widget_dict is None:
                raise Http404("field_id not found")
            if widget_dict.pop("url") != self.request.path:
                raise Http404("field_id was issued for the view.")
        qs, qs.query = widget_dict.pop("queryset")
        self.queryset = qs.all()
        widget_dict["queryset"] = self.queryset
        widget_cls = widget_dict.pop("cls")
        return widget_cls(**widget_dict)
```

widget_dict is found. However, the db is hit every time on:
`self.queryset = qs.all()`

In settings.py:

```
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "select2": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
}
SELECT2_CACHE_BACKEND = "select2"

```
The controls works fine. The data is in the dropdown. Redis has the keys.
I checked the postgres logs and I see multiple SELECTS every time I hit the dropdown.

Am I setting something up wrong?

Any thoughts would be appreciated.

Thanks

**Comment by codingjoe** [comment]
Hi @andyp05,

Thanks for reaching out. You are experiencing the intended behavior. To give you a little more context we do not actually cache all possible select options. This would be very slow and you would need a huge cache server. We merely use the cache as a persistent store across multiple application servers to store query data. However, the query is executed every time you search for options. Yet not the whole query is executed but the query that matches your search term. Beyond that, the query is also paginated to ensure fast response times.

I hope my explanation could shed a little light on the inner workings of this package. As a side note maybe: it's probably never a good idea to cache a `Queryset` in Django. Your database should know best what to cache (load in memory) by itself.

Best,
Joe

**Comment by andyp05** [comment]
Thanks for the quick response and explanation.
