### ISSUE TITLE
Add id to html so javascript can be easely used.

### ISSUE THREAD

**Issue by vdveldet** [codingjoe/django-select2#94]
Select2 can be used in combination with javascript to return the value(s) selected.
In html id is used to bind event listeners, for instance populate other fields upon change.
```
  $('#id_reference').change(function(){
    alert($(this).val());
    console.log("id_reference changed")
  })

  $('#reference').change(function(){
    alert($(this).val());
    console.log("reference changed")
  })
```

It is unclear what the id is from the django_select2 components since this is generated dynamically.

When a model is defined
```
Class Product(models.Model):
    reference = models.CharField(null=True, blank=True, max_length=100)
    description = models.TextField(null=True, blank=True)
....
```
The reference is a s2forms.ModelSelect2Widget component and upon selection this should fill up the description filed (this is ajax query to other refecence)

In order to perform this a clear view is needed on the generated id so function like below can be used.
```
  $('#id_reference').change(function(){
    alert($(this).val());
    console.log("id_reference changed")
  })

  $('#reference').change(function(){
    alert($(this).val());
    console.log("reference changed")
  })
```

**Comment by codingjoe** [comment]
Hi @vdveldet,

Thank you for reaching out. All form elements do include idea by default in Django. If you need help using the select2 API, I suggest looking into their doku. They have a couple of extra events, you might want to listen too. See also https://select2.org/

Best,
Joe
